### ISSUE TITLE
Can I just evaluate the results on the test set but not submit them to the leaderboard?

### ISSUE THREAD

**Issue by Jizma** [ubc-vision/image-matching-benchmark#25]
Hi, it is a good benchmark for image matching community, but some times,  I would like to just use it to improve our method rather than participate in the challenge directly.

**Comment by kmyi** [comment]
In that case you can use the validation sets, or whatever split you desire. It should be an easy fix. We won’t be able to release the test sets, since we intend to keep the challenge going for at lease a few years.

Thanks

Message written with iPhone. 
Please excuse any brievity and typos.
—
Kwang Moo YI
Assistant Professor
Dept. of Computer Science
University of Victoria
+1 (250) 475 5837

**Comment by Jizma** [comment]
Thank you for your answer
